apiVersion: v1
kind: Service
metadata:
  name: tomcat
  labels:
    app: tomcat

spec:
  ports:
  - name: tomcat
    port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: tomcat
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-webapp
  labels:
    app: tomcat

spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - image: mohamedafrid/tomcat-deploy
          name: tomcat-webapp
          ports:
            - containerPort: 8080
              name: tomcat

          
    
